### PR TITLE
Increase Energy Output of Ultimate Energy Cubes

### PR DESCRIPTION
**Pull request by XredstonemodsX**
Increases the energy output from Mekanism's ultimate energys cubes

### CODE REVIEW

**Comment by DraksterAU** [comment]
Reason for this ?

**Comment by XredstonemodsX** [comment]
Energy Cubes are the only devices I'm aware of acting as a liason between EU power and Tesseracts, and since it has a limited draw you cannot power more than a few things at a time.

**Comment by DraksterAU** [comment]
EU output is limited. That's what the problem is :)

Going to reject this as we will have an RF zpm / naquadah power interface that supports higher output. Same for EU.

It will be here in a few days with the major update.

**Comment by XredstonemodsX** [comment]
It's not EU output, as the Cube stays full indefinitly, but not enough power can be drained to support all systems

**Comment by DraksterAU** [comment]
You need to use more than one cube then...

**Comment by DraksterAU** [comment]
Oh so you mean the cube inputs at the same rate it outputs?

This is normal for all devices that are not transformers..?

**Comment by XredstonemodsX** [comment]
No, as far as  can tell the imput is not limited, but the output is. Thats not the issue tho, the issue is that the output cannot support many machines when it's all divided amoungst them

**Pull request closed without merging**
