### PR TITLE
Kull Warrior

### PR DESCRIPTION
**Pull request by mainesi**
Adds Kull Warrior, with chance of incursions and spawning in the milkyway galaxy - Boss Type NPC

### CODE REVIEW

**Comment by XredstonemodsX** [comment]
If this is a boss then 10% is much too high.

**Comment by Bysokar** [comment]
10% what? Your comment makes no sense whatsoever

**Comment by Bysokar** [comment]
Please use the sound for the Kull warrior weapon, not the staff?

**Comment by Bysokar** [comment]
Please use the sound for the Kull warrior weapon, not the staff?

**Comment by Bysokar** [comment]
Please use the sound for the Kull warrior weapon, not the staff?

**Comment by Bysokar** [comment]
Please use the sound for the Kull warrior weapon, not the staff?

**Comment by XredstonemodsX** [comment]
"If this is a boss then 10% is much too high for an incursion chance." The last edit was 18 hours ago, long before you commented, so it seems like you're at this point either bad at reading or are just trying to be an ass

**Comment by Bysokar** [comment]
It didn't say incursion chance when I looked at it @redstone.

**Comment by mainesi** [comment]
cant find the kull weapon sound sorry

**Pull request merged**
