### PR TITLE
Adds some items

### PR DESCRIPTION
**Pull request by XredstonemodsX**
Completes about 1% of the configs for market, but some nice items to have on nonetheless

### CODE REVIEW

**Comment by Bysokar** [comment]
Typos. Again.
Hint: ` is not part of a valid material name... read before you submit :)

**Comment by XredstonemodsX** [comment]
I didn't touch any material names though _-_

**Comment by Bysokar** [comment]
https://github.com/StargateMC/StargateMCPublic/pull/219/commits/7058a6f50f774c6d59ee9cd2f9415b427ee80a36#diff-fd88b0bcbc8b66077e8f8ee1055e0fbbR4131

Your commit changed it.

**Comment by XredstonemodsX** [comment]
fixed

**Pull request merged**
